name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update next.config.js for static export
        run: |
          if [ -f "next.config.js" ]; then
            CONFIG_FILE="next.config.js"
          elif [ -f "next.config.mjs" ]; then
            CONFIG_FILE="next.config.mjs"
          else
            echo "No next.config.js or next.config.mjs found, creating one"
            CONFIG_FILE="next.config.js"
            echo "module.exports = {}" > $CONFIG_FILE
          fi
          
          # Backup the original config
          cp $CONFIG_FILE ${CONFIG_FILE}.backup
          
          # Add or update the output property to 'export'
          if grep -q "module.exports" $CONFIG_FILE; then
            # CommonJS format
            sed -i -e 's/module.exports\s*=\s*{/module.exports = {\n  output: "export",/g' $CONFIG_FILE
          elif grep -q "export default" $CONFIG_FILE; then
            # ES module format
            sed -i -e 's/export default\s*{/export default {\n  output: "export",/g' $CONFIG_FILE
          else
            # Create a new config
            echo "module.exports = { output: 'export' }" > $CONFIG_FILE
          fi

      - name: Build static export
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler pages deploy out --project-name=infinirewards-docs
