name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Add Edge Runtime to route files
        run: |
          # Add edge runtime to api/search.js or ts
          if [ -f "app/api/search/route.js" ]; then
            SEARCH_FILE="app/api/search/route.js"
          elif [ -f "app/api/search/route.ts" ]; then
            SEARCH_FILE="app/api/search/route.ts"
          elif [ -f "pages/api/search.js" ]; then
            SEARCH_FILE="pages/api/search.js"
          elif [ -f "pages/api/search.ts" ]; then
            SEARCH_FILE="pages/api/search.ts"
          else
            echo "Search API file not found in expected locations"
            find . -name "search.js" -o -name "search.ts" -o -name "route.js" -o -name "route.ts" | grep -i api
          fi
          
          if [ -n "$SEARCH_FILE" ] && [ -f "$SEARCH_FILE" ]; then
            echo "Adding edge runtime to $SEARCH_FILE"
            sed -i '1s/^/export const runtime = "edge";\n\n/' "$SEARCH_FILE"
          fi
          
          # Add edge runtime to docs/[[...slug]] page
          if [ -d "app/docs" ]; then
            find app/docs -name "page.js" -o -name "page.tsx" | while read -r file; do
              echo "Adding edge runtime to $file"
              sed -i '1s/^/export const runtime = "edge";\n\n/' "$file"
            done
          elif [ -f "pages/docs/[[...slug]].js" ]; then
            echo "Adding edge runtime to pages/docs/[[...slug]].js"
            sed -i '1s/^/export const runtime = "edge";\n\n/' "pages/docs/[[...slug]].js"
          elif [ -f "pages/docs/[[...slug]].tsx" ]; then
            echo "Adding edge runtime to pages/docs/[[...slug]].tsx"
            sed -i '1s/^/export const runtime = "edge";\n\n/' "pages/docs/[[...slug]].tsx"
          fi

      - name: Install Cloudflare Pages adapter
        run: npm install -D @cloudflare/next-on-pages

      - name: Add build script to package.json
        run: |
          npx json -I -f package.json -e 'this.scripts["pages:build"]="npx @cloudflare/next-on-pages"'

      - name: Build for Cloudflare Pages
        run: npm run pages:build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler pages deploy .vercel/output/static --project-name=infinirewards-docs
