name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install next-on-pages
        run: npm install --save-dev @cloudflare/next-on-pages

      - name: Create wrangler.toml
        run: |
          cat > wrangler.toml << EOL
          name = "infinirewards-docs"
          compatibility_date = "2024-09-23"
          compatibility_flags = ["nodejs_compat"]
          pages_build_output_dir = ".vercel/output/static"
          EOL

      - name: Add edge runtime to server routes
        run: |
          # Ensure API route uses the Edge runtime
          mkdir -p .edge-runtime-temp
          
          # Find all API and dynamic route files
          find . -path "*/api/**/route.js" -o -path "*/api/**/route.ts" -o -path "*/api/**/route.tsx" | while read -r file; do
            if ! grep -q "export const runtime" "$file"; then
              echo "Adding Edge runtime to $file"
              cp "$file" ".edge-runtime-temp/$(basename "$file")"
              echo 'export const runtime = "edge";' > "$file"
              cat ".edge-runtime-temp/$(basename "$file")" >> "$file"
            fi
          done
          
          # Also check Pages router API files
          find ./pages -path "*/api/*.js" -o -path "*/api/*.ts" -o -path "*/api/*.tsx" 2>/dev/null | while read -r file; do
            if ! grep -q "export const runtime" "$file"; then
              echo "Adding Edge runtime to $file"
              cp "$file" ".edge-runtime-temp/$(basename "$file")"
              echo 'export const runtime = "edge";' > "$file"
              cat ".edge-runtime-temp/$(basename "$file")" >> "$file"
            fi
          done
          
          # Check for dynamic route files in app directory
          find ./app -name "page.js" -o -name "page.tsx" | while read -r file; do
            if ! grep -q "export const runtime" "$file"; then
              echo "Adding Edge runtime to $file"
              cp "$file" ".edge-runtime-temp/$(basename "$file")"
              echo 'export const runtime = "edge";' > "$file"
              cat ".edge-runtime-temp/$(basename "$file")" >> "$file"
            fi
          done
          
          # Check for dynamic route files in pages directory
          find ./pages -name "[[*]].js" -o -name "[[*]].tsx" 2>/dev/null | while read -r file; do
            if ! grep -q "export const runtime" "$file"; then
              echo "Adding Edge runtime to $file"
              cp "$file" ".edge-runtime-temp/$(basename "$file")"
              echo 'export const runtime = "edge";' > "$file"
              cat ".edge-runtime-temp/$(basename "$file")" >> "$file"
            fi
          done
          
          # Clean up temp directory
          rm -rf .edge-runtime-temp

      - name: Build for Cloudflare Pages
        run: npx @cloudflare/next-on-pages
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler pages deploy .vercel/output/static --project-name=infinirewards-docs
