name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update next.config.js for static export
        run: |
          # Check if next.config.js exists and create/modify as needed
          if [ -f "next.config.js" ]; then
            # Backup original config
            cp next.config.js next.config.js.bak
            
            # Add/update output export config
            sed -i 's/module.exports = /module.exports = Object.assign(/' next.config.js
            echo ", { output: 'export' })" >> next.config.js
          else
            # Create a basic config file with static export
            echo "module.exports = { output: 'export' };" > next.config.js
          fi
          
          cat next.config.js

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler pages deploy out --project-name=infinirewards-docs
